### ISSUE TITLE
RIDEN 6012P power supply: code issue with going higher than 6 A

### ISSUE THREAD

**Issue by brennmat** [mbrennwa/pypsucurvetrace#14]
When the 6012P is configured at high-current mode (12A range), the code goes wrong when it tries to get a reading where the current is higher than 6A. Is there something going on with register #20?

**Comment by mbrennwa** [comment]
Fixed with SVN revision #431. Problem was the OVP and OCP settings interfered with the required voltage / current values at the RIDEN PSU unit.
